[package]
name = "shared"
version = "0.1.0"
edition = "2021"


[dependencies]
#native-tls = "0.2.10"
log = "0.4.17"
pretty_env_logger = "0.4.0"
#  TRAER LAS DEPENDENCIAS EXTERNAS NECESARIAS. Revisar lib.rs de este package
